export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_BY_FEATURED = ' GET_PRODUCTS_BY_FEATURED'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_SUB_CATEGORIES = 'GET_SUB_CATEGORIES'
